### ISSUE TITLE
[Motivating Scenario] Structure an Organization

### ISSUE THREAD

**Issue by gnardin** [HyperAgents/hmas#112]
This issue relates to the motivating scenario for the structuring of an organization in HMAS.

**Comment by vcharpenay** [comment]
here is feedback from today's internal meeting at EMSE:
- `q7` seems to be a competency question of a different kind compared to other: as incompatibilities are defined so far (as SHACL shapes), an agent would to submit a SPARQL query, it would instead evaluate the SHACL shape specifying incompatibilities (`ex:incompatibilityShape`) on the graph specifying the organization (`FL_Logistics`).

**Comment by FabienGandon** [comment]
@gnardin can we close this issue as addressed in PR #165  ?

**Comment by gnardin** [comment]
@FabienGandon This issue is addressed in and linked to the PR #165 . Whenever the PR is accepted, this issue will be closed. My suggestion is to keep this issue open until the PR is finalized.
