### ISSUE TITLE
What types of resources can be modelled as hmas:Workspace?

### ISSUE THREAD

**Issue by andreiciortea** [HyperAgents/hmas#138]
I'm opening this issue to discuss the use of the term [hmas:Workspace](https://purl.org/hmas/Workspace) — and to regroup some of the discussions from f2f meetings and email conversations. Two questions that surfaced in the discussion of Issue #122 are:
- is an [hmas:Workspace](https://purl.org/hmas/Workspace) a subclass of [hmas:Artifact](https://purl.org/hmas/Artifact)?
- is an [hmas:Workspace](https://purl.org/hmas/Workspace) hostable (i.e., can it be hosted on an [hmas:HypermediaMASPlatform](https://purl.org/hmas/HypermediaMASPlatform))?

Long write-up, but I tried to keep it structured, concise, and self-contained. Concrete proposals for the core ontology and its usage are at the very end.

To open the discussion, consider the following examples:
- a factory building:
  - the factory building is a non-information resource that exists in the physical world
  - the factory building can contain agents (e.g., factory workers), industrial devices, tools, and the agents' activities
  - all this can be described in an [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile)
- a workspace on [Yggdrasil](https://github.com/Interactions-HSG/jade-hypermedia), which implements [Agents & Artifacts](https://link.springer.com/article/10.1007/s10458-010-9140-7) (as part of the [JaCaMo](https://github.com/jacamo-lang/jacamo) meta-model):
  - the workspace can contain [Jason](https://github.com/jason-lang/jason) agents, [CArtAgO](https://github.com/cartago-lang/cartago) artifacts, other workspaces, and the agents' activities 
  - the workspace is implemented as an instance of the CArtAgO [Workspace](https://github.com/CArtAgO-lang/cartago/blob/master/src/main/java/cartago/Workspace.java) class; agents do not interact with the workspace directly: they interact with the workspace via an artifact, which is an instance of the CArtAgO [WorkspaceArtifact](https://github.com/CArtAgO-lang/cartago/blob/master/src/main/java/cartago/WorkspaceArtifact.java) class
  - both the workspace and the workspace artifact are hosted on Yggdrasil
  - the workspace artifact has an [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile) that exposes [hmas:Signifier](https://purl.org/hmas/Signifier)s for interacting with the workspace, and links to [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile)s of contained resources
- a container on [JADE-hypermedia](https://github.com/Interactions-HSG/jade-hypermedia), which implements the [FIPA Abstract Architecture](http://fipa.org/specs/fipa00001/SC00001L.html) (in the interpretation given by the [JADE](https://jade.tilab.com/) platform):
  - the container can contain JADE agents and their activities (e.g., interactions with other agents)
  - the container has an [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile) that describes the container and links to [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile)s of contained agents
- a [Linked Data Platform (LDP) Container](https://www.w3.org/TR/ldp/#dfn-linked-data-platform-container): the LDP Container is an [LDP RDF Source](https://www.w3.org/TR/ldp/#dfn-linked-data-platform-container), which is an [LDP Resource](https://www.w3.org/TR/ldp/#dfn-linked-data-platform-resource) whose state is _fully represented_ in RDF (see also [RDF Source](https://www.w3.org/TR/rdf11-concepts/#dfn-rdf-source)); the LDP defines three types of containers:
  - [LDP Basic Container](https://www.w3.org/ns/ldp#BasicContainer): can only contain documents (i.e., information resources) and links to the contained documents via containment triples using [ldp:contains](https://www.w3.org/ns/ldp#contains) as predicate
  - [LDP Direct Container](https://www.w3.org/ns/ldp#DirectContainer): in addition to containment triples with [ldp:contains](https://www.w3.org/ns/ldp#contains), it can use custom membership triples (e.g., a membership triple using [foaf:knows](http://xmlns.com/foaf/0.1/#term_knows) as predicate), and can contain any resources (i.e., not only documents)
  - [LDP Indirect Container](https://www.w3.org/ns/ldp#IndirectContainer): similar to an LDP Direct Container with the difference that the object of a membership triple can be derived from the content of a contained document
    - for example, if I post a [foaf:PersonalProfileDocument](http://xmlns.com/foaf/0.1/#term_PersonalProfileDocument) to an LDP Indirect Container, the object of the membership triple can be derived from a triple with property [foaf:primaryTopic](http://xmlns.com/foaf/0.1/#term_primaryTopic) contained within the profile document and identifying the person described by the profile document (e.g., `<#andrei>`); in contrast, if I am using an LDP Direct Container, the derived object of the membership triple would the profile document itself

From these examples:
- I generally understand an [hmas:Workspace](https://purl.org/hmas/Workspace) to refer to something else than a document, i.e. it is a non-information resource
- I see the factory building, an Yggdrasil workspace, or a JADE-hypermedia container as good examples of [hmas:Workspace](https://purl.org/hmas/Workspace):
  - they contain agents and their activities; the factory building and the Yggdrasil workspace can also contain artifacts or other resources agents use in their activities
  - they are all examples of non-information resources that can be described by [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile)s
- I understand an LDP Direct/Indirect Container to be closer to an [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile) that describes an [hmas:Workspace](https://purl.org/hmas/Workspace) (rather than an actual [hmas:Workspace](https://purl.org/hmas/Workspace))
  - both would use [hmas:contains](https://purl.org/hmas/contains) as the predicate of membership triples (in addition to containment triples using [ldp:contains](https://www.w3.org/ns/ldp#contains) as predicate)
  - the containment and membership triples are managed by the LDP according to the W3C Recommendation
- we can use an LDP Basic Container to describe an [hmas:Workspace](https://purl.org/hmas/Workspace) but clients would have to manage the membership triples
  - this is an important point because, to the best of my knowledge, most existing implementations of Solid platforms use LDP Basic Containers (I might be wrong)
- the factory building is a physical entity and cannot be hosted on an [hmas:HypermediaMASPlatform](https://purl.org/hmas/HypermediaMASPlatform) (but its [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile) can be hosted)
- the Yggdrasil workspace and the JADE-hypermedia container are examples of workspaces that are hosted on an [hmas:HypermediaMASPlatform](https://purl.org/hmas/HypermediaMASPlatform)
- conceptually, I understand an [hmas:Workspace](https://purl.org/hmas/Workspace) to be something different from an [hmas:Artifact](https://purl.org/hmas/Artifact): the workspace contains agents and their activities, which may use artifacts and other resources
- I do not see a fundamental reason for requiring an [hmas:Artifact](https://purl.org/hmas/Artifact) similar to the workspace artifact in CArtAgO in order to allow agents to interact with an [hmas:Workspace](https://purl.org/hmas/Workspace) — but it might be useful in some cases
  - e.g., we currently use workspace artifacts on Yggdrasil because the implementation is based on CArtAgO

Concrete proposals for the core ontology and its usage:
- to make [hmas:Workspace](https://purl.org/hmas/Workspace) a subclass of [hmas:Hostable](https://purl.org/hmas/Hostable); note here that [hmas:Hostable](https://purl.org/hmas/Hostable) is not just for documents / information resources (it already includes agents)
  - [**later edit, I think I was rushing too much to wrap up the conclusions**] if we consider the factory building to be an [hmas:Workspace](https://purl.org/hmas/Workspace), then clearly we cannot define all workspaces to be [hmas:Hostable](https://purl.org/hmas/Hostable) (but some of them are, which we could model in various ways)
- to maintain that [hmas:Workspace](https://purl.org/hmas/Workspace) and [hmas:Artifact](https://purl.org/hmas/Artifact) are disjoint classes
- to maintain that [hmas:Agent](https://purl.org/hmas/Agent), [hmas:Artifact](https://purl.org/hmas/Artifact), [hmas:Workspace](https://purl.org/hmas/Workspace), and [hmas:HypermediaMASPlatform](https://purl.org/hmas/HypermediaMASPlatform) generally refer to non-information resources described by [hmas:ResourceProfile](https://purl.org/hmas/ResourceProfile)s
  - I would extend this point to [hmas:Organization](https://purl.org/hmas/Organization) as well (cc @gnardin @oboissier)

**Comment by FabienGandon** [comment]
All changes are implemented in the latest Core.ttl
