### ISSUE TITLE
Label of hmas:contains is currently "directly contains"

### ISSUE THREAD

**Issue by andreiciortea** [HyperAgents/hmas#139]
I noticed that the `rdfs:label` of `hmas:contains` is "directly contains":
https://github.com/HyperAgents/ns.hyperagents.org/blob/6142a2177822e5d5dfafd4520d9fe9155dccefef/src/core.ttl#L214-L220

Is this the intended label or do we need to update it?

**Comment by FabienGandon** [comment]
I propose we maintain this label to capture the difference between `:isTransitivelyContainedIn` and `:contains` 
Alternatives are:
-  change le label to "contains"
- have two labels: "directly contains" and "contains"
