### ISSUE TITLE
A need to define a domain as a union between BehaviorSpecification and BehaviorExecution

### ISSUE THREAD

**Issue by DrLeturc** [HyperAgents/hmas#143]
Hi,

In order to regulate behaviors I must describe which are the effect of actions (behaviors).
In standard action logics (STIT, BIAT, PDL,...), it is defined as the possible worlds that a behavior "brings it about" (BIAT) or "sees to it that" (STIT).

Indeed the effect of actions are the set of possible worlds that the behavior brings it about. This will allow for me to deduce what could be the prohibited/obliged behaviors w.r.t. the state of affairs that we aim to prevent from (e.g. for prohibitions) /or aim to reach (e.g. for obligations))...

Thus, I introduced in the regulation vocabulary a property :
```
:bringsItAbout rdf:type owl:ObjectProperty ;
    rdfs:isDefinedBy :regulation ;
    rdfs:domain hmas:Behavior ;
    rdfs:range :PossibleWorld ;
    rdfs:comment "A specification which defines what a behavior brings it about. "@en ;
    rdfs:label "brings it about"@en .
```

This class `hmas:Behavior` intends to be defined as the union of `hmas:BehaviorSpecification` and  `hmas:BehaviorExecution`. It could be a superclass of these two classes for instance ?

Can you adapt the interaction ontology w.r.t. that request ? Or propose me a method for describing in an elegant way the domain of my property `:bringsItAbout` as the union of these two classes ? : )

PS : by the way, if I consider standard semantics of STIT logics, I think the name of this property should be rather a "sees to it that" since  the "brings it about" is semantically defined in the literature as a neighborhood function on 2^{2^W} and here we are defining in the same way a binary relation...

**Comment by FabienGandon** [comment]
yes using a union in a range or domain is feasible.
NB: hmas:BehaviorSpecification is deprecated cf #116
