### ISSUE TITLE
A question about hosts and isHostedOn

### ISSUE THREAD

**Issue by YoucTagh** [HyperAgents/hmas#175]
In [core.ttl](https://github.com/HyperAgents/hmas/blob/master/src/core.ttl#L320) `:hosts` states:

> A relation that refers to an information resource or a process (e.g., agent) ...

And `isHostedOn` states: 

> ... that hosts the resource.

Is it an information resource or a resource?

Also, the `:hosts` relation is missing the `owl:inverseOf` relation (all others have an `owl:inverseOf`).

If editing is required, I will also point to a trailing space in the `rdfs:comment` value of `isHostedOn`.

**Comment by FabienGandon** [comment]
- From a logical point of view: `owl:inverseOf` is symmetric therefore  `:isHostedOn owl:inverseOf :hosts`  implies the `:hosts owl:inverseOf :isHostedOn`.
- From an editorial point of view we should decide and apply for all definitions a rule : repeat or not the symmetric. I have no strong preference here and can leave with both options.
- From the comment point of view the inversion of the signature should be captured i.e. if the range is "resource or a process" (resp. "resource") the domain of the inverse should be "resource or a process" (resp "resource"). Personally, I would only use "resource".

any preferences? opinions?

**Comment by YoucTagh** [comment]
I agree with what you said @FabienGandon.

> any preferences? opinions?

Me neither, I have no strong preference.

**Comment by smnmyr** [comment]
Editorially: I would keep the owl:inverseOf only in the active versions (i.e., :hosts, :exposesSignifier, etc.). If this is objectionable, I would duplicate it for readability.

What was the reason for putting "(information) resource or process" instead of just "resource"? The rest of the comment only talks about the resource. Possibly this can be simplified throughout?

**Comment by andreiciortea** [comment]
The reasoning behind talking about "information resources or processes" for `hmas:hosts` was to try and be as precise as possible: on an origin server, we can only host data or processes, i.e. programs in execution (agents, artifacts, etc.). The second sentence in the comment talks about resources to refer to both. If the current formulation is confusing, another proposal would be to use "documents or processes" instead.

We could also rephrase the comment to talk about resources in general and then provide examples, but then I think the natural language definition would be unnecessarily broad.

**Comment by FabienGandon** [comment]
As discussed in the heartbeat meeting  03/11/2023 a first update could be
`:isHostedOn  rdfs:comment "A relation that refers to the platform that hosts the information resource or a process (e.g., agent). "@en`
this also corrects the typo "A relations" to "A relation"

**Comment by Antoine-Zimmermann** [comment]
I think we concluded that we should not mention "agents" as an example of a process (leaving the choice of considering software agents as processes open). This means updating both the comment of `:hosts` and `:isHostedOn`:

```
:hosts  rdfs:comment "A relation that refers to an information resource or a process that is hosted on a platform. A hosting relation might have further implications, e.g. the usage of the hosted resource (or the usage of platform resources by the hosted resource) could be subject to terms of service or data licensing policies specific to the hosting platform."@en ;
...
:isHostedOn rdfs:comment "A relation that refers to the platform that hosts the information resource or a process. "@en
```

We could also replace "(e.g., agent)" by "(e.g., a running program)".

**Comment by FabienGandon** [comment]
this issue is now covered in PR #186
