### ISSUE TITLE
Should we use XDTesting for the automation process of the project ?

### ISSUE THREAD

**Issue by DrLeturc** [HyperAgents/hmas#67]
[XDTesting](https://fiorelaciroku.github.io/XD-Testing/) proposes automation tool for  [eXtreme Design](https://extremedesign.info/) ontology modelling methodology, to keep track on the progress of an automated test management using Github Actions. 

To have a look on this project, you can access to their GitHub repository [here](https://github.com/FiorelaCiroku/XDTestingSession).

They propose an interesting way to use github to deploy ontologies.

Would you agree we apply this framework ?

**Comment by FabienGandon** [comment]
I have the feeling that this issue may have been obsoleted by the latest works on our own script.
@NicoRobertIn could you confirm that? or is [XDTesting](https://fiorelaciroku.github.io/XD-Testing/) bringing additional things we are missing?

**Comment by NicoRobertIn** [comment]
My script was made for model tests, while this tool seems to be more for data test and query test
So this tool would be more complementary to what is already in the branch *test-workflow*

**Comment by DrLeturc** [comment]
Thanks, are you agree that I can close this issue now ?
